
[[constraint]]
  name = "github.com/getkin/kin-openapi"
  branch = "master"

[[constraint]]
  name = "github.com/grokify/gotilla"
  branch = "master"

[[constraint]]
  name = "github.com/andrewcretin/swaggman"
  branch = "master"

