site_name: Swaggman
repo_url: https://github.com/grokify/swaggman
edit_uri: tree/master/docs
docs_dir: docs
theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: "None"

nav:
    - Home: index.md
    - OpenAPI3Lint:
        - Overview: openapi3lint.md
    - OpenAPI 3 Inspect:
        - Missing Descriptions: openapi3/inspect/missing_descriptions.md
